# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

inversa <- function(M) {
    .Call(`_ARCensReg_inversa`, M)
}

ciclobeta <- function(X, phi, SAEMu, SAEMuyi, SAEMuzi) {
    .Call(`_ARCensReg_ciclobeta`, X, phi, SAEMu, SAEMuyi, SAEMuzi)
}

ComputeMean <- function(yobs, Xmatrix, beta, phi) {
    .Call(`_ARCensReg_ComputeMean`, yobs, Xmatrix, beta, phi)
}

ComputeVar <- function(sigma2, Pphi, phi, SAEMu) {
    .Call(`_ARCensReg_ComputeVar`, sigma2, Pphi, phi, SAEMu)
}

Gradient <- function(x, saemU, saemY, phi, beta, sigma2, nu, fixnu) {
    .Call(`_ARCensReg_Gradient`, x, saemU, saemY, phi, beta, sigma2, nu, fixnu)
}

GradientExp <- function(saemLU, saemU, uy2, uyw, uw2, A, B, phi, beta, sigma2, nu, fixnu) {
    .Call(`_ARCensReg_GradientExp`, saemLU, saemU, uy2, uyw, uw2, A, B, phi, beta, sigma2, nu, fixnu)
}

HessianExp <- function(saemU, saemUZi, saemUYi, uy2, uyw, uw2, A, B, media, X, phi, beta, sigma2, nu, fixnu) {
    .Call(`_ARCensReg_HessianExp`, saemU, saemUZi, saemUYi, uy2, uyw, uw2, A, B, media, X, phi, beta, sigma2, nu, fixnu)
}

